package paqeteEntity;

// Generated 18/07/2014 08:32:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "episunsa_gradesTracker")
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private String nombres;
	private String apellidos;
	private String correo;
	private Byte bloqueado;
	private Date ultimoIngreso;
	private Date fechaRegistro;
	private Date fechaNacimiento;
	private Byte comprobado;
	private Set<RolesUsuarios> rolesUsuarioses = new HashSet<RolesUsuarios>(0);

	public Usuarios() {
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
	}

	public Usuarios(String username, String password, String nombres,
			String apellidos, String correo, Byte bloqueado,
			Date ultimoIngreso, Date fechaRegistro, Date fechaNacimiento,
			Byte comprobado, Set<RolesUsuarios> rolesUsuarioses) {
		this.username = username;
		this.password = password;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.correo = correo;
		this.bloqueado = bloqueado;
		this.ultimoIngreso = ultimoIngreso;
		this.fechaRegistro = fechaRegistro;
		this.fechaNacimiento = fechaNacimiento;
		this.comprobado = comprobado;
		this.rolesUsuarioses = rolesUsuarioses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 32)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nombres", nullable = false, length = 128)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "apellidos", nullable = false, length = 128)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "correo", length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "bloqueado")
	public Byte getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(Byte bloqueado) {
		this.bloqueado = bloqueado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ultimo_ingreso", length = 19)
	public Date getUltimoIngreso() {
		return this.ultimoIngreso;
	}

	public void setUltimoIngreso(Date ultimoIngreso) {
		this.ultimoIngreso = ultimoIngreso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_registro", length = 19)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "comprobado")
	public Byte getComprobado() {
		return this.comprobado;
	}

	public void setComprobado(Byte comprobado) {
		this.comprobado = comprobado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios")
	public Set<RolesUsuarios> getRolesUsuarioses() {
		return this.rolesUsuarioses;
	}

	public void setRolesUsuarioses(Set<RolesUsuarios> rolesUsuarioses) {
		this.rolesUsuarioses = rolesUsuarioses;
	}

}
